/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DealershipsRouteImport } from './routes/dealerships'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as FeaturedRouteImport } from './routes/featured'
import { Route as FinancingRouteImport } from './routes/financing'
import { Route as GetEstimateRouteImport } from './routes/get-estimate'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as InventoryBodyRouteImport } from './routes/inventory.$body'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DealershipsRoute = DealershipsRouteImport.update({
  id: '/dealerships',
  path: '/dealerships',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturedRoute = FeaturedRouteImport.update({
  id: '/featured',
  path: '/featured',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancingRoute = FinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => rootRouteImport,
} as any)
const GetEstimateRoute = GetEstimateRouteImport.update({
  id: '/get-estimate',
  path: '/get-estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryBodyRoute = InventoryBodyRouteImport.update({
  id: '/inventory/$body',
  path: '/inventory/$body',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/buy': typeof BuyRoute
  '/calculator': typeof CalculatorRoute
  '/coming-soon': typeof ComingSoonRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/dealerships': typeof DealershipsRoute
  '/faqs': typeof FaqsRoute
  '/featured': typeof FeaturedRoute
  '/financing': typeof FinancingRoute
  '/get-estimate': typeof GetEstimateRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/news': typeof NewsRoute
  '/reviews': typeof ReviewsRoute
  '/saved': typeof SavedRoute
  '/sell': typeof SellRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/inventory/$body': typeof InventoryBodyRoute
  '/listings/$id': typeof ListingsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/buy': typeof BuyRoute
  '/calculator': typeof CalculatorRoute
  '/coming-soon': typeof ComingSoonRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/dealerships': typeof DealershipsRoute
  '/faqs': typeof FaqsRoute
  '/featured': typeof FeaturedRoute
  '/financing': typeof FinancingRoute
  '/get-estimate': typeof GetEstimateRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/news': typeof NewsRoute
  '/reviews': typeof ReviewsRoute
  '/saved': typeof SavedRoute
  '/sell': typeof SellRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/inventory/$body': typeof InventoryBodyRoute
  '/listings/$id': typeof ListingsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/buy': typeof BuyRoute
  '/calculator': typeof CalculatorRoute
  '/coming-soon': typeof ComingSoonRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/dealerships': typeof DealershipsRoute
  '/faqs': typeof FaqsRoute
  '/featured': typeof FeaturedRoute
  '/financing': typeof FinancingRoute
  '/get-estimate': typeof GetEstimateRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/news': typeof NewsRoute
  '/reviews': typeof ReviewsRoute
  '/saved': typeof SavedRoute
  '/sell': typeof SellRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/inventory/$body': typeof InventoryBodyRoute
  '/listings/$id': typeof ListingsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/agents'
    | '/auth'
    | '/buy'
    | '/calculator'
    | '/coming-soon'
    | '/compare'
    | '/contact'
    | '/dealerships'
    | '/faqs'
    | '/featured'
    | '/financing'
    | '/get-estimate'
    | '/new-arrivals'
    | '/news'
    | '/reviews'
    | '/saved'
    | '/sell'
    | '/services'
    | '/terms'
    | '/admin'
    | '/blog/$slug'
    | '/inventory/$body'
    | '/listings/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/agents'
    | '/auth'
    | '/buy'
    | '/calculator'
    | '/coming-soon'
    | '/compare'
    | '/contact'
    | '/dealerships'
    | '/faqs'
    | '/featured'
    | '/financing'
    | '/get-estimate'
    | '/new-arrivals'
    | '/news'
    | '/reviews'
    | '/saved'
    | '/sell'
    | '/services'
    | '/terms'
    | '/admin'
    | '/blog/$slug'
    | '/inventory/$body'
    | '/listings/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/404'
    | '/about'
    | '/agents'
    | '/auth'
    | '/buy'
    | '/calculator'
    | '/coming-soon'
    | '/compare'
    | '/contact'
    | '/dealerships'
    | '/faqs'
    | '/featured'
    | '/financing'
    | '/get-estimate'
    | '/new-arrivals'
    | '/news'
    | '/reviews'
    | '/saved'
    | '/sell'
    | '/services'
    | '/terms'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/inventory/$body'
    | '/listings/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRoute
  AuthRoute: typeof AuthRoute
  BuyRoute: typeof BuyRoute
  CalculatorRoute: typeof CalculatorRoute
  ComingSoonRoute: typeof ComingSoonRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  DealershipsRoute: typeof DealershipsRoute
  FaqsRoute: typeof FaqsRoute
  FeaturedRoute: typeof FeaturedRoute
  FinancingRoute: typeof FinancingRoute
  GetEstimateRoute: typeof GetEstimateRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  NewsRoute: typeof NewsRoute
  ReviewsRoute: typeof ReviewsRoute
  SavedRoute: typeof SavedRoute
  SellRoute: typeof SellRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  InventoryBodyRoute: typeof InventoryBodyRoute
  ListingsIdRoute: typeof ListingsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealerships': {
      id: '/dealerships'
      path: '/dealerships'
      fullPath: '/dealerships'
      preLoaderRoute: typeof DealershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/featured': {
      id: '/featured'
      path: '/featured'
      fullPath: '/featured'
      preLoaderRoute: typeof FeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financing': {
      id: '/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof FinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-estimate': {
      id: '/get-estimate'
      path: '/get-estimate'
      fullPath: '/get-estimate'
      preLoaderRoute: typeof GetEstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$body': {
      id: '/inventory/$body'
      path: '/inventory/$body'
      fullPath: '/inventory/$body'
      preLoaderRoute: typeof InventoryBodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRoute,
  AuthRoute: AuthRoute,
  BuyRoute: BuyRoute,
  CalculatorRoute: CalculatorRoute,
  ComingSoonRoute: ComingSoonRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  DealershipsRoute: DealershipsRoute,
  FaqsRoute: FaqsRoute,
  FeaturedRoute: FeaturedRoute,
  FinancingRoute: FinancingRoute,
  GetEstimateRoute: GetEstimateRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  NewsRoute: NewsRoute,
  ReviewsRoute: ReviewsRoute,
  SavedRoute: SavedRoute,
  SellRoute: SellRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  InventoryBodyRoute: InventoryBodyRoute,
  ListingsIdRoute: ListingsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
